

// Array
let num = [10, 20, 30, 40, 50]

// console.log(num[2]);
// console.log(num.length);
// num[10] = 100;
// console.log(num.length);

// let p = Array.from(1235)
// console.log(p);

let i = num.length - 1;
for (let n of num) {
    console.log(num[i]);
    i--;
}

let nm = [10, 20, 30, 40, 50]
nm[10] = 100;
console.log(nm); //[ 10, 20, 30, 40, 50, <5 empty items>, 100 ]
nm[6] = 60
console.log(nm); //[ 10, 20, 30, 40, 50, <1 empty item>, 60, <3 empty items>, 100 ]


// Array with const keyword

const vb = [1, 2, 3, 4, 5, 6]
const vb = [10, 20, 30, 40]








































































